### PR TITLE
added hooks for query modification in DoctrineORM locator

### PR DESCRIPTION
**Pull request by pulse00**
To allow modifications on the doctrine queries during composite location without overriding the complete `locate` logic.

### CODE REVIEW

**Comment by smarques** [comment]
nice

**Comment by stephpy** [comment]
Thanks ;)

**Comment by stephpy** [comment]
I created a tag: https://github.com/stephpy/timeline-bundle/releases/tag/2.2.0. :)

**Comment by pulse00** [comment]
@stephpy thanks for the quick merge!

**Comment by stephpy** [comment]
You're welcome.

**Pull request merged**
