### PR TITLE
Added doctrine <2.6 to conflicts

### PR DESCRIPTION
**Pull request by core23**
This should fix https://github.com/stephpy/timeline-bundle/issues/187

### CODE REVIEW

**Comment by stephpy** [comment]
Nice catch !

**Comment by stephpy** [comment]
I created a tag https://github.com/stephpy/timeline-bundle/releases/tag/v2.5.1

**Comment by core23** [comment]
Sure this is a patch release? This will drop support for old php releases.

**Comment by stephpy** [comment]
Mmmmh, You mean it has to be considered as a BC break ?

**Comment by stephpy** [comment]
You're right, I create a 3.0.0 and remove this one.

**Pull request merged**
